### ISSUE TITLE
Support for bytea

### ISSUE THREAD

**Issue by sporto** [giacomocavalieri/squirrel#12]
Hi, this looks really neat, will like to use it. But I use `bytea` extensively, which is not supported.
https://www.postgresql.org/docs/current/datatype-binary.html
Could you add support for this?
Thanks

**Comment by giacomocavalieri** [comment]
Support for `bytea` landed in [v1.5.0](https://github.com/giacomocavalieri/squirrel/releases/tag/v1.5.0) :)

**Comment by sporto** [comment]
Thank you
