### ISSUE TITLE
Labelled args

### ISSUE THREAD

**Issue by sporto** [giacomocavalieri/squirrel#14]
The code generated relies on positional arguments. E.g.

```gleam
pub fn users__create(db, arg_1, arg_2, arg_3) {
```

This isn't optimal as it is easy to pass arguments in the wrong order.
Looking at the function signature is not clear either.

I wonder if we could use labelled arguments here? e.g.

```gleam
pub fn users__create(db db, email arg_1, name arg_2, password arg_3) {
```

**Comment by giacomocavalieri** [comment]
I thought about it but couldn't find a way to do it besides with some custom comments, which I don't find particularly nice. As far as I'm aware Postgres doesn't let you name the holes of a prepared statement, does it?

**Comment by sporto** [comment]
I have been looking at how this is done via a prepare statement. I haven't found anything to get the names of the holes. :(

**Comment by giacomocavalieri** [comment]
Yeah that's unfortunate because it would be a great feature! I think only SQLite supports named query parameters
