### ISSUE TITLE
Broken video embed in `README.md`

### ISSUE THREAD

**Issue by thabnir** [giacomocavalieri/squirrel#18]
The embedded video in the `README.md` just shows up as a link on Firefox and Chrome, and only actually embeds the video on Safari (and GitHub mobile and Safari on iOS, haven't tested Android).

<img width="497" alt="video is linked with missing img icon" src="https://github.com/user-attachments/assets/2c396158-7a91-4d14-9c20-743f6b82d4b2">

It doesn't have the alt text, but if you change the line

```md
![Squirrel showcase](https://github.com/user-attachments/assets/4abd308b-b191-4296-a0b6-093db0595794)
```

to

```md
https://github.com/user-attachments/assets/4abd308b-b191-4296-a0b6-093db0595794
```

it goes from

![Squirrel showcase](https://github.com/user-attachments/assets/4abd308b-b191-4296-a0b6-093db0595794)

to

https://github.com/user-attachments/assets/4abd308b-b191-4296-a0b6-093db0595794

Screenshot of the difference on Chrome if you can't test on a non-Safari browser:

<img width="772" alt="video fails to embed properly on top, succeeds on bottom" src="https://github.com/user-attachments/assets/7b734f6d-0d1a-4fb6-8e18-386e1faa68a8">

**Comment by giacomocavalieri** [comment]
Thank you! It should be fixed now 🙂
