### ISSUE TITLE
Document usage of the timestamp type

### ISSUE THREAD

**Issue by Rhal95** [giacomocavalieri/squirrel#31]
I tried querying a timestamp from my database like this:
```sql
select creation_time from session;
```
Squirrel generated the code for it without problems.
When using the generated code I get an error like this 
```console
Error(UnexpectedResultType([DecodeError("timestamp", "Tuple of 2 elements", ["5"])]))
```

I searched the Discord and found out that I was supposed to query timestamps like this:
```sql
select date_trunc('second', creation_time) as creation_time from session;
```

This should be part of the documentation.
It would be even better if squirrel had better error messages for timestamps or showed a warning when trying to use a timestamp without the truncation.

**Comment by giacomocavalieri** [comment]
Mmh that's interesting, that sounds like a bug either in squirrel or in pgo. Definitely something I should fix instead of generating code that fail at runtime!

Thank you for reporting this!!

**Comment by Rhal95** [comment]
This is not a problem with squirrel.

gleam_pgo decodes timestamps as `#(#(Int, Int, Int), #(Int, Int, Int))` which breaks when pgo sends `#(#(Int, Int, Int), #(Int, Int, Float))`.
There is [this PR](https://github.com/lpil/pgo/pull/36) that addresses that but it is not merged yet.

So there is nothing to do except waiting for the PR to be merged.
Sorry for the noise

**Comment by giacomocavalieri** [comment]
No worries, thank you for pointing this out anyway!!
