### ISSUE TITLE
Duplicate column names on joins should fail with a helpful error message

### ISSUE THREAD

**Issue by eolculnamo2** [giacomocavalieri/squirrel#34]
Squirrel  generates type constructors with duplicate field names. In the below example, I do an inner join and get two uuids, and two aliases because both tables in the join have the fields. Instead, it would be nice for squirrel to detect duplicates and give a helpful error.

```
select * from timesheet_templates
inner join timesheet_template_questions 
on timesheet_templates.uuid = timesheet_template_questions.template_fk
where timesheet_templates.uuid = $1 and timesheet_templates.org_fk = $2;

```

```
pub type FindTemplateWithQuestionsByIdRow {
  FindTemplateWithQuestionsByIdRow(
    uuid: String,
    alias: String,
    published: Bool,
    org_fk: Option(String),
    user_fk: Option(String),
    uuid: String,
    alias: String,
    template_fk: String,
    kind: String,
    a: Option(String),
    b: Option(String),
    c: Option(String),
    d: Option(String),
    correct_answer: Option(String),
  )
}


pub fn find_template_with_questions_by_id(db, arg_1, arg_2) {
  let decoder =
    decode.into({
      use uuid <- decode.parameter
      use alias <- decode.parameter
      use published <- decode.parameter
      use org_fk <- decode.parameter
      use user_fk <- decode.parameter
      use uuid <- decode.parameter
      use alias <- decode.parameter
      use template_fk <- decode.parameter
      use kind <- decode.parameter
      use a <- decode.parameter
      use b <- decode.parameter
      use c <- decode.parameter
      use d <- decode.parameter
      use correct_answer <- decode.parameter
      FindTemplateWithQuestionsByIdRow(
        uuid: uuid,
        alias: alias,
        published: published,
        org_fk: org_fk,
        user_fk: user_fk,
        uuid: uuid,
        alias: alias,
        template_fk: template_fk,
        kind: kind,
        a: a,
        b: b,
        c: c,
        d: d,
        correct_answer: correct_answer,
      )
    })

```

**Comment by giacomocavalieri** [comment]
Yeah I agree it should fail with a nice error message in case of duplicate fields, thank you!

**Comment by eolculnamo2** [comment]
I'd love to try to open a PR for this. Do you think it would be better for squirrel to find some way alter duplicate names instead of returning an error? Naively, a field called "foo" could have a second in the record called "foo_2," but maybe that's still confusing. Maybe we could use something from the table name to suffix duplicate fields so that if there's two tables bar and baz that both have foo fields, it would produce foo_bar and foo_baz?

An error works too, but I think that means that someone using select * is going to have to go back and specify each field they want out of there query explicitly which is sort of a pain.

**Comment by giacomocavalieri** [comment]
Oh yeah please go ahead if you want to give it a try! 💖

I want squirrel to be explicit about this kind of problems, for example when one picks a name that is not a valid gleam identifier it fail instead of trying to turn it into one.
I think it should explicitly fail instead this case too, I'd rather have names be an intentional choice rather than left up to squirrel

**Comment by eolculnamo2** [comment]
LIfe's gotten busy, and I'd hate to block someone else from taking this issue. If anyone else wants to take it, go ahead!

**Comment by giacomocavalieri** [comment]
Thank you for letting me know! I've fixed this in <https://github.com/giacomocavalieri/squirrel/commit/6f775f88fd540c44e7c389d1c2f62a41d6aa6b90>, so this will be fixed on the next release!
