### ISSUE TITLE
Timestamps fail to decode due to microseconds

### ISSUE THREAD

**Issue by ceedon** [giacomocavalieri/squirrel#37]
The current implementation of the timestamp decoder fails for the timestamp field when used w/ common pg built-ins like `now()` as they store microseconds.

Is this intentional?
Could store the last item of the second tuple as a Float and support both.

**Comment by giacomocavalieri** [comment]
Hello! I think that's a bug in `gleam_pgo` and not squirrel itself as it's just calling `pgo.decode_timestamp`, I think it might be worth opening this issue in that repo

**Comment by ceedon** [comment]
Fair enough!
