### ISSUE TITLE
Dynamic query example

### ISSUE THREAD

**Issue by sysint64** [giacomocavalieri/squirrel#39]
Hi, it would be nice to show how you can deal with dynamically changed queries like filters on a marketplace, if it's a even possible with the library.

**Comment by sysint64** [comment]
Yeah, this is the example from sqlx on rust: 

Took this example from [stackoverflow](https://stackoverflow.com/questions/74956100/how-to-build-safe-dynamic-query-with-sqlx-in-rust).

```rust
use sqlx::{query_builder::QueryBuilder, Execute};

struct Search {
    id: i64,
    username: Option<String>,
    min_age: Option<i8>,
    max_age: Option<i8>,
}

fn search_query(search: Search) -> String {
    let mut query = QueryBuilder::new("SELECT * from users where id = ");
    query.push_bind(search.id);

    if let Some(username) = search.username {
        query.push(" AND username = ");
        query.push_bind(username);
    }

    if let Some(min_age) = search.min_age {
        query.push(" AND age > ");
        query.push_bind(min_age);
    }

    if let Some(max_age) = search.max_age {
        query.push(" AND age < ");
        query.push_bind(max_age);
    }

    query.build().sql().into()
}

fn main() {
    dbg!(search_query(Search {
        id: 12,
        username: None,
        min_age: None,
        max_age: None,
    })); // "SELECT * from users where id = $1"
    dbg!(search_query(Search {
        id: 12,
        username: Some("Bob".into()),
        min_age: None,
        max_age: None,
    })); // "SELECT * from users where id = $1 AND username = $2"
    dbg!(search_query(Search {
        id: 12,
        username: Some("Bob".into()),
        min_age: Some(10),
        max_age: Some(70),
    })); // "SELECT * from users where id = $1 AND username = $2 AND age > $3 AND age < $4"
}
```

**Comment by giacomocavalieri** [comment]
Ah I see, thank you for the example! It's not possible to compose a query dynamically like that with Squirrel as it only (intentionally) works with plain old `.sql` files. But you could use that final query directly and let squirrel generate the code
```sql
select
  *
from
  users
where
  id = $1
  and username = $2
  and age > $3
  and age < $4;
```

**Comment by sysint64** [comment]
I see, do you plan eventually support it? I'm not sure if that last example would work with optional fields, e.g. if a user hasn't provided the age, may Squirrel automatically detect it and generate query without age filter??

**Comment by giacomocavalieri** [comment]
No, Squirrel doesn't generate any queries, it only uses the query you write to create type-safe wrappers around those without creating new ones
