### ISSUE TITLE
Queries fail to generate with Squirrel v2.0.2 but work with v2.0.0

### ISSUE THREAD

**Issue by brettkolodny** [giacomocavalieri/squirrel#44]
```sql
select * from users;
```
In v2.0.2:
```
Error: Invalid query [42601]

    ╭─ ./src/sql/test_t.sql
    │
  1 │ select * from users;
  2 │
    ┆
```

This is happening to all my queries

**Comment by brettkolodny** [comment]
I can provide more details if needed but it was getting late and wanted to put this up before I forgot

**Comment by brettkolodny** [comment]
Sorry! I'll put together a report to demonstrate the issue tomorrow morning!

**Comment by giacomocavalieri** [comment]
Hello! Do you have any updates on this?

**Comment by brettkolodny** [comment]
Sorry! Peaked the talk about the Postgres versions and thought this was closed without me. I can confirm that updating to the newest version of squirrel now gives me the error: `Error: Outdated Postgres version`! 

I'm currently using v15, and for no particular reason. Thanks for all the work!

**Comment by giacomocavalieri** [comment]
Lovely, thank you!
