### ISSUE TITLE
Support for DATABASE_URL or similar

### ISSUE THREAD

**Issue by michaeljones** [giacomocavalieri/squirrel#6]
It seems quite common in tooling these days to put all the connection information in a single environment variable as a url.

It would be handy for squirrel to support this too.

An example can be seen in the dbmate docs: https://github.com/amacneil/dbmate?tab=readme-ov-file#connecting-to-the-database

I hope this is sufficient information to go off.

**Comment by giacomocavalieri** [comment]
Thank you for the suggestion! Now you can use a `DATABASE_URL` env variable with a connection string in [v1.3.0](https://github.com/giacomocavalieri/squirrel/releases/tag/v1.3.0)
