### ISSUE TITLE
Support for uuid type

### ISSUE THREAD

**Issue by ktandun** [giacomocavalieri/squirrel#9]
Hiya 👋 , firstly thank you for making this library. Its been awesome experience so far!

One thing that would make it perfect for me is support for `uuid` type since most of the time my primary key uses that. 
I've gotten around it so far by casting it to `varchar` when querying data, but when inserting I don't think we can do that(?)

```
   Compiled in 0.20s
    Running squirrel.main
Error: Unsupported type

    ╭─ ./src/traveller/sql/create_user_trip.sql
    │
  1 │ INSERT INTO user_trips (userid, tripid)
  2 │     VALUES ($1, $2);
  3 │
  4 │
    ┆
One of the rows returned by this query has type `uuid` which I cannot currently generate code for.

If you would like for this type to be supported, please open an issue at https://github.com/giacomocavalieri/squirrel/issues/new
```

**Comment by giacomocavalieri** [comment]
I've added support for uuids in [v1.4.0](https://github.com/giacomocavalieri/squirrel/releases/tag/v1.4.0), thanks for the patience!
